/**
 * submission-created — the two emails an order request produces.
 *
 * The filename is the contract: Netlify invokes a function named
 * `submission-created` automatically on every successful form submission, with
 * the submission in `payload`. Nothing to register, nothing to keep in sync.
 *
 * It sends two things:
 *
 *   1. To the buyer — an acknowledgement, so they know it arrived and hold the
 *      reference number in writing.
 *   2. To Kent — the working notification, with the order laid out and a
 *      pre-addressed reply button.
 *
 * Kent's notification duplicates the one Netlify sends natively. That is
 * deliberate: Netlify's is generated by Netlify's own infrastructure and keeps
 * working if Resend is down, so it stays on as the safety net. This one exists
 * because Netlify's template cannot be customised, and the single most valuable
 * thing here — a reply button that carries the reference into the subject line —
 * requires control of the HTML.
 *
 * Guarantees, in priority order:
 *   1. Never break a submission. The order is already stored before this runs,
 *      so every failure path returns 200 and logs. A failed email must never
 *      look like a failed order.
 *   2. Never send to the wrong person. Contact-form submissions are ignored.
 *   3. Say only what is true. The buyer's mail promises the personal reply Kent
 *      actually sends, and states plainly that nothing has been charged. It is
 *      an acknowledgement, not a receipt.
 */

const SITE = 'https://www.kentosborn.studio';
const EMBLEM = `${SITE}/og-keyhole-square-notext.jpg`;

// kentosborn.studio has no MX records, so the From address cannot receive
// anything. Replies are steered to a real inbox; people do reply to these.
const FROM = 'Keyhole Mystic Publishing <orders@kentosborn.studio>';
const KENT_INBOX = 'ayahuaskent@gmail.com';

// Who receives the working notification. Kent is deliberately absent until the
// flow has been exercised end to end by a human.
const NOTIFY = ['barias@axiscode.com'];

// Images are capped so a large order cannot turn the email into a wall of
// pictures — the thing that makes a first-contact message read as spam.
const MAX_THUMBS = 6;

const esc = (s) =>
  String(s ?? '').replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])
  );
const money = (n) => Number(n || 0).toLocaleString('en-US');

/** The subject both customer-facing messages share, so they thread together. */
const threadSubject = (id) => `Request received — ${id}`;

function parseItems(raw) {
  try {
    const arr = JSON.parse(raw || '[]');
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

const totals = (items) =>
  items.reduce(
    (acc, it) => ({
      usd: acc.usd + Number(it.u || 0) * Number(it.q || 1),
      mxn: acc.mxn + Number(it.m || 0) * Number(it.q || 1),
    }),
    { usd: 0, mxn: 0 }
  );

/** Order lines as an HTML table. Thumbnails only while under the cap. */
function itemRows(items, withThumbs) {
  return items
    .map((it, idx) => {
      const showImg = withThumbs && idx < MAX_THUMBS && it.i;
      const line = Number(it.u || 0) * Number(it.q || 1);
      const lineM = Number(it.m || 0) * Number(it.q || 1);
      return `
      <tr>
        ${showImg
          ? `<td width="64" style="padding:10px 12px 10px 0;vertical-align:top;">
               <img src="${esc(it.i)}" width="56" alt="" style="display:block;width:56px;height:auto;border-radius:4px;border:1px solid #e6e0d8;">
             </td>`
          : '<td width="0" style="padding:0;"></td>'}
        <td style="padding:10px 0;vertical-align:top;font:15px/1.45 -apple-system,Segoe UI,Roboto,sans-serif;color:#27211E;">
          <strong>${esc(it.q)} × ${esc(it.t)}</strong><br>
          <span style="color:#6b6259;font-size:14px;">${esc(it.v)}${it.e ? ` · ${esc(it.e)}` : ''}</span>
        </td>
        <td align="right" style="padding:10px 0 10px 12px;vertical-align:top;white-space:nowrap;font:14px/1.45 -apple-system,Segoe UI,Roboto,sans-serif;color:#27211E;">
          $${money(line)} USD<br><span style="color:#6b6259;">$${money(lineM)} MXN</span>
        </td>
      </tr>`;
    })
    .join('');
}

function itemsText(items) {
  return items
    .map((it) => `  ${it.q} × ${it.t} — ${it.v}${it.e ? ` (${it.e})` : ''}  $${money(Number(it.u||0)*Number(it.q||1))} USD / $${money(Number(it.m||0)*Number(it.q||1))} MXN`)
    .join('\n');
}

const shell = (inner) => `<!doctype html><html><body style="margin:0;padding:0;background:#f6f3ee;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f6f3ee;padding:24px 12px;">
<tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border:1px solid #e6e0d8;border-radius:8px;">
${inner}
</table>
</td></tr></table></body></html>`;

// ---------------------------------------------------------------- buyer email
function buyerEmail({ name, id, items, country }) {
  const t = totals(items);
  const greeting = name ? `Hi ${name.split(' ')[0]},` : 'Hello,';

  const html = shell(`
  <tr><td style="padding:28px 28px 8px;">
    <img src="${EMBLEM}" width="56" alt="Keyhole Mystic Publishing"
         style="display:block;width:56px;height:56px;border-radius:50%;">
    <div style="font:13px/1.4 -apple-system,Segoe UI,Roboto,sans-serif;letter-spacing:.14em;text-transform:uppercase;color:#9F8C82;padding-top:14px;">
      Keyhole Mystic Publishing
    </div>
    <div style="font:22px/1.3 Georgia,serif;color:#27211E;padding-top:4px;">
      Kent Osborn — Kentchi
    </div>
  </td></tr>
  <tr><td style="padding:18px 28px 0;font:16px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;color:#27211E;">
    <p style="margin:0 0 14px;">${esc(greeting)}</p>
    <p style="margin:0 0 14px;">Your request reached the studio. <strong>Nothing has been charged and nothing is committed</strong> — this simply opens the conversation.</p>
    <p style="margin:0 0 6px;">Your reference</p>
    <p style="margin:0 0 20px;font:20px/1.2 Georgia,serif;color:#34045C;">${esc(id)}</p>
  </td></tr>
  <tr><td style="padding:0 28px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid #e6e0d8;">
      ${itemRows(items, true)}
      <tr><td colspan="3" style="border-top:1px solid #e6e0d8;padding-top:12px;font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#27211E;">
        <strong>Estimated total: $${money(t.usd)} USD / $${money(t.mxn)} MXN</strong><br>
        <span style="color:#6b6259;font-size:14px;">before shipping — Kent will confirm the final figure for ${esc(country || 'your country')}</span>
      </td></tr>
    </table>
  </td></tr>
  <tr><td style="padding:20px 28px 30px;font:16px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;color:#27211E;">
    <p style="margin:0 0 14px;">Kent will reply personally with a quote including shipping. If you need to add anything meanwhile, just reply to this email — it reaches him directly.</p>
    <p style="margin:0;color:#6b6259;font-size:14px;">Every deck ships with its guidebook.</p>
  </td></tr>`);

  const text = [
    greeting,
    ``,
    `Your request reached the studio. Nothing has been charged and nothing is`,
    `committed yet — this simply opens the conversation.`,
    ``,
    `Your reference: ${id}`,
    ``,
    `What you asked about:`,
    itemsText(items) || '  (no items listed)',
    ``,
    `Estimated total: $${money(t.usd)} USD / $${money(t.mxn)} MXN (before shipping)`,
    ``,
    `Kent will reply personally with a quote including shipping. If you need to`,
    `add anything meanwhile, just reply to this email.`,
    ``,
    `Every deck ships with its guidebook.`,
    ``,
    `— Keyhole Mystic Publishing · Kent Osborn (Kentchi)`,
  ].join('\n');

  return { html, text };
}

// ----------------------------------------------------------------- Kent email
function kentEmail({ id, country, name, email, address, notes, items, arrived }) {
  const t = totals(items);
  // The reply carries the SAME subject the buyer already has, so their side
  // stays one thread — and deliberately omits the estimate: it is a triage aid
  // for this inbox, not something to put in front of a customer, and it changes
  // the moment the order is adjusted.
  // The address stays LITERAL. It sits in the mailto path, where "@" is legal —
  // percent-encoding it to %40 yields a technically valid URI that Gmail cannot
  // parse a recipient from, so the compose window opens with an empty To field.
  // Only subject and body are encoded; those are query parameters, where
  // reserved characters genuinely must be escaped.
  //
  // No body by default, and that is the point: Gmail only inserts the sender's
  // signature when it composes a blank message. Supplying a body tells it the
  // message is already written, and the signature is silently dropped. An opener
  // is worth far less than Kent's real signature — which can carry formatting
  // and links a mailto body never could, since mailto bodies are plain text.
  //
  // Set REPLY_BODY_TEMPLATE (Netlify env var) to override, accepting {name} and
  // {id}. Doing so reintroduces the signature loss; that is the trade.
  const template = process.env.REPLY_BODY_TEMPLATE;
  const body = template
    ? template.replace(/\{name\}/g, (name || '').split(' ')[0] || 'there').replace(/\{id\}/g, id)
    : '';
  const mailto =
    `mailto:${email}` +
    `?subject=${encodeURIComponent(threadSubject(id))}` +
    (body ? `&body=${encodeURIComponent(body)}` : '');

  const html = shell(`
  <tr><td style="padding:24px 28px 4px;font:13px/1.4 -apple-system,Segoe UI,Roboto,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:#9F8C82;">
    Order request · ${esc(country)}
  </td></tr>
  <tr><td style="padding:0 28px;font:22px/1.25 Georgia,serif;color:#27211E;">
    ${esc(id)} — est. $${money(t.usd)} USD
  </td></tr>
  <tr><td style="padding:16px 28px 0;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid #e6e0d8;">
      ${itemRows(items, true)}
      <tr><td colspan="3" style="border-top:1px solid #e6e0d8;padding-top:12px;font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#27211E;">
        <strong>Estimated subtotal: $${money(t.usd)} USD / $${money(t.mxn)} MXN</strong>
        <span style="color:#6b6259;font-size:14px;">— before shipping</span>
      </td></tr>
    </table>
  </td></tr>
  <tr><td style="padding:22px 28px 0;font:15px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;color:#27211E;border-top:1px solid #e6e0d8;">
    <strong>${esc(name)}</strong><br>
    <a href="mailto:${esc(email)}" style="color:#34045C;">${esc(email)}</a><br>
    ${address ? `<span style="color:#6b6259;white-space:pre-line;">${esc(address)}</span>` : '<span style="color:#9F8C82;">no address given yet</span>'}
  </td></tr>
  <tr><td style="padding:18px 28px 4px;">
    <a href="${esc(mailto)}" data-reply-button style="display:inline-block;background:#34045C;color:#ffffff;text-decoration:none;font:15px/1 -apple-system,Segoe UI,Roboto,sans-serif;padding:14px 22px;border-radius:6px;">
      Reply to ${esc((name || 'them').split(' ')[0])} →
    </a>
    <div style="font:13px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#9F8C82;padding-top:8px;">
      Opens a reply titled “${esc(threadSubject(id))}” — keeps the thread together.
    </div>
  </td></tr>
  ${notes ? `<tr><td style="padding:18px 28px 0;">
    <div style="border-left:3px solid #D0AC68;padding:2px 0 2px 14px;font:15px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;color:#27211E;white-space:pre-line;">${esc(notes)}</div>
  </td></tr>` : ''}
  ${arrived ? `<tr><td style="padding:20px 28px 26px;">
    <div style="font:12px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;color:#6b6259;background:#faf8f5;border:1px solid #eee8e0;border-radius:6px;padding:12px;white-space:pre-line;">${esc(arrived)}</div>
  </td></tr>` : '<tr><td style="padding:0 0 26px;"></td></tr>'}`);

  const text = [
    `${id} — ${country} — est. $${money(t.usd)} USD`,
    ``,
    itemsText(items) || '  (no items listed)',
    ``,
    `Estimated subtotal: $${money(t.usd)} USD / $${money(t.mxn)} MXN (before shipping)`,
    ``,
    `${name} <${email}>`,
    address || 'no address given yet',
    ``,
    notes ? `Notes: ${notes}\n` : '',
    arrived || '',
    ``,
    `Reply keeping the thread: ${mailto}`,
  ].join('\n');

  return { html, text };
}

async function send(key, message) {
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify(message),
  });
  if (!res.ok) throw new Error(`Resend ${res.status}: ${await res.text()}`);
  return res.json();
}

export default async (req) => {
  const ok = () => new Response('ok', { status: 200 });

  let payload;
  try {
    ({ payload } = await req.json());
  } catch (err) {
    console.error('submission-created: unreadable body —', err.message);
    return ok();
  }

  const formName = payload?.form_name ?? '';
  if (!formName.startsWith('order-request')) {
    console.log(`submission-created: ignoring form "${formName}"`);
    return ok();
  }

  const d = payload.data ?? {};
  const id = (d.enquiry_id ?? '').trim() || '(no reference)';
  const buyer = (d.email ?? '').trim();
  const items = parseItems(d.order_items);

  const key = process.env.RESEND_API_KEY;
  if (!key) {
    console.error('submission-created: RESEND_API_KEY not set — no mail sent');
    return ok();
  }

  const common = {
    id,
    country: d.country ?? '',
    name: d.name ?? '',
    email: buyer,
    items,
  };

  // Kent's working copy first: if only one of the two can get through, the
  // business needs the order more than the buyer needs the acknowledgement.
  try {
    const mail = kentEmail({ ...common, address: d.address, notes: d.notes, arrived: d.how_they_arrived });
    await send(key, {
      from: FROM,
      to: NOTIFY,
      // NOT the buyer: a stray "reply" here would carry the estimate in its
      // subject straight to them. Kent's own inbox is the harmless default.
      reply_to: KENT_INBOX,
      subject: `RFQ [${id}]: ${d.country ?? ''}${totals(items).usd ? ` — $${money(totals(items).usd)} USD` : ''}`,
      html: mail.html,
      text: mail.text,
    });
    console.log(`submission-created: ${id} — notified ${NOTIFY.join(', ')}`);
  } catch (err) {
    console.error(`submission-created: ${id} — notification failed:`, err.message);
  }

  if (!buyer) {
    console.warn(`submission-created: ${id} has no buyer email; nothing to acknowledge`);
    return ok();
  }
  try {
    const mail = buyerEmail(common);
    await send(key, {
      from: FROM,
      to: [buyer],
      reply_to: KENT_INBOX,
      subject: threadSubject(id),
      html: mail.html,
      text: mail.text,
    });
    console.log(`submission-created: ${id} — acknowledged to ${buyer}`);
  } catch (err) {
    console.error(`submission-created: ${id} — acknowledgement failed:`, err.message);
  }

  return ok();
};
